### ISSUE TITLE
issue: thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { pos: 2:6, kind:

### ISSUE THREAD

**Issue by fkgruber** [durka/karaconv#7]
I'm trying to convert my xlm I used in the old karabiner and I got the following error:

./karaconv -i ~/OneDrive/Documents/emacs/karabiner/private.xml -o ~/.config/karabiner/karabiner.json 
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { pos: 2:6, kind: Syntax("Invalid processing instruction: <?xml") }', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.

It is pretty simple and small. just want to prevent karabiner to use it when I'm on vnc or emacs.

Here is the file:
https://gist.github.com/fkgruber/9c39fa2e8b46bb7648a2efe74d1ff398

**Comment by a2902793** [comment]
Got the same error too, except mine ended with a "libcore/result.rs:1009:5"

**Comment by akidee** [comment]
Same error here with the 0.3 binary:

`$ karaconv -i ....xml -o ....json
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: missing field `appendix`', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.`

File: https://gist.github.com/akidee/ca0d815ac0ec2c1b852acf47c46959d2
